name: Go
on:
  push:
    branches:
      - master
  pull_request:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: echo commit sha
      run: echo ${{ github.event.pull_request.head.sha }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
      id: go

    - name: Test
      run: go test -v .
