name: issue-test

on:
  issues:
    types: labeled

jobs:
  print_detail:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          ISSUE_TITLE: ${{ github.event.issue.title}}
          ISSUE_LINK: ${{ github.event.issue.html_url }}
        run: |
          echo $ISSUE_TITLE
          echo $ISSUE_LINK
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: sminamot/github-actions-test-private
          path: external
          #token: ${{ secrets.EX_GITHUB_TOKEN }}
      - name: ls
        run: |
          ls
          ls external
