name: issue-test

on:
  issues:
    types: opened

jobs:
  print_detail:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          ISSUE_TITLE: ${{ github.event.issue.title}}
          ISSUE_LINK: ${{ github.event.issue.html_url }}
        run: |
          echo $ISSUE_TITLE
          echo $ISSUE_LINK
          echo ${{ github.event.issue }}
