name: Create git tag
on:
  push:
    branches:
      - master

jobs:
  build:
    name: create_tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: env
      run: |
        echo TAG_NAME=$(TZ=Asia/Tokyo date +'%Y%m%d%H%M%S') >> $GITHUB_ENV
        git tag -a "$TAG_NAME" -m "$TAG_NAME" --cleanup=whitespace
        git push origin $TAG_NAME
