name: Test
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      BRANCH: ${GITHUB_REF##*/}
    steps:
    - name: Echo
      run: |
        echo $GITHUB_REF
        echo ${GITHUB_REF##*/}
        echo ${BRANCH}
        echo ${{ github.repository }}
