name: Test
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo $GITHUB_REF
        echo ${GITHUB_REF##*/}
        echo ${{ github.repository }}
        echo ::set-env name=branch::${GITHUB_REF##*/}

    - name: Echo2
      run: |
        echo $branch
