name: Test
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      BRANCH:
    steps:
    - name: Echo
      run: |
        echo $GITHUB_REF
        echo ${GITHUB_REF##*/}
        BRANCH=${GITHUB_REF##*/}
        echo $BRANCH
        echo ${{ github.repository }}

    - name: Echo2
      run: |
        echo $BRANCH
