name: Test
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      REPOSITORY: {{ github.repository }}
    steps:
    - name: Echo
      run: |
        echo $GITHUB_REF
        echo ${GITHUB_REF##*/}
        echo $REPOSITORY

    - name: Echo2
      run: |
        echo $REPOSITORY
