name: Test
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo $GITHUB_REF
        echo ${GITHUB_REF##*/}
        echo ${GITHUB_REF##*/d}
